# Base Holo toolchain for SteamOS
# Uncomment one of the alternatives below for Rust or Go support:
# FROM ghcr.io/steamdeckhomebrew/holo-toolchain-rust:latest
# FROM ghcr.io/steamdeckhomebrew/holo-toolchain-go:latest
FROM ghcr.io/steamdeckhomebrew/holo-base:latest

# entrypoint.sh should always be located in the backend folder
ENTRYPOINT [ "/backend/entrypoint.sh" ]
